
import { create } from 'zustand'
const useJobcardsStore = create((set) => ({
  currentUser: null,
  currentWorkstation: null,
  currentOperation: null,
  currentJobcard: null,
  currentOpt: null,
  currentBarkod: null,
  jobCardList: [],
  tesDetayList: [],
  employee: null,
  isLoading: false,
  isAllSelected:false,
  isAllProfileTransferred: false,
  isAccessoryLoading:false,
  errorModalVisible:false,
  filters: [],
  maxSanalAdet:0,
  qualityCheckCode:0,  
  setMaxSanalAdet: (maxSanalAdet) => set({ maxSanalAdet: maxSanalAdet }),
  setQualityCheckCode: (qualityCheckCode) => set({ qualityCheckCode: qualityCheckCode }),
  setCurrentUser: (user) => set({ currentUser: user }),
  setCurrentWorkstation: (workstation) => set({ currentWorkstation: workstation }),
  setCurrentOperation: (operation) => set({ currentOperation: operation }),
  setCurrentJobcard: (jobcard) => set({ currentJobcard: jobcard }),
  setCurrentOpt: (opt) => set({ currentOpt: opt }),
  setCurrentBarkod: (barkod) => set({ currentBarkod: barkod }),
  setJobCardList: (list) => set({ jobCardList: list }),
  setTesDetayList: (list) => set({ tesDetayList: list }),
  setEmployee: (employee) => set({ employee: employee }),
  setIsLoading: (isLoading) => set({ isLoading: isLoading }),
  setErrorModalVisible: (errorModalVisible) => set({ errorModalVisible: errorModalVisible }),
  setIsAllSelected: (isAllSelected) => set({ isAllSelected: isAllSelected }),
  setIsAllProfileTransferred: (isAllProfileTransferred) => set({ isAllProfileTransferred: isAllProfileTransferred }),
  setFilters: (filters) => set({ filters: filters }),
  setIsAccessoryLoading: (isAccessoryLoading) => set({ isAccessoryLoading: isAccessoryLoading }),
}));

export default useJobcardsStore;